apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: thalia
  namespace: argocd
spec:
  description: Thalia Project - History
  destinations:
    - namespace: prod
      server: https://kubernetes.default.svc
    - namespace: dev
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:tikalk/argocd-demo.git
