apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
spec:
  description: Staging Environments
  destinations:
    - namespace: staging
      server: https://34.73.77.97
  sourceRepos:
    - git@github.com:khealth/infra.git
