apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-dev-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:tikalk/argocd-demo.git"
    path: envs/dev-2
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
