apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: "Dev environments"
  destinations:
    - namespace: "dev*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:tikalk/argocd-demo.git
