# namePrefix: dev-
commonLabels:
  variant: dev
commonAnnotations:
  note: Hello, I am dev!
resources:
  # - git@github.com/khealth/test-env//base
  - ../../base
  - ingress.yaml
patchesStrategicMerge:
  - hpa.yaml
images:
  - name: "arabkin/hello-cloudbuild"
    newTag: "v1.2.4"
