# namePrefix: production-
commonLabels:
  variant: production
commonAnnotations:
  note: Hello, I am production!
resources:
  # - git@github.com/khealth/test-env//base
  - ../../base
patchesStrategicMerge:
  - hpa.yaml
images:
  - name: "arabkin/hello-cloudbuild"
    newTag: "v1.0.0"
