apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  description: Production Environments
  destinations:
    - namespace: prod
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:tikalk/argocd-demo.git
