apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stage
  namespace: argocd
spec:
  description: Staging Environments
  destinations:
    - namespace: stage
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:tikalk/argocd-demo.git
