apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  namespace: argocd
spec:
  project: stage
  source:
    repoURL: "git@github.com:tikalk/argocd-demo.git"
    path: env/stage
    targetRevision: master
  destination:
    server: "https://34.73.77.97"
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
